Add cypress test to profile
crdschurch/crds-profile pull request #47
Opened 2020-10-02 13:34 UTC by lynchl607

Add cypress test to profile
Add vault functionality

2020-10-02 17:09 UTC, s-henney requested changes
You've added good coverage here, nice job!
You should alias and reuse elements to make tests more readable though. I included an example in the Contact Login Tab suite, and you can checkout Cypress's examples [here](https://docs.cypress.io/api/commands/get.html#Alias).

2020-10-02 17:09 UTC, s-henney commented on package.json
> +    "cypress": "^5.2.0",
Could you add a script to the 'scripts' section that'll kick off Cypress? I normally include one that runs in headless mode with the int_crossroads.json config file.

2020-10-09 13:42 UTC, lynchl607 commented on cypress/integration/profille/contact_and_login_tab_spec.js
> +    cy.get('crds-phone'  , { includeShadowDom: true }).get('[placeholder="Mobile Number"]', { includeShadowDom: true }).type('555', { force: true });
The  { force: true } is necessary with out it I get a disabled element error.

2020-10-10 00:09 UTC, s-henney requested changes
I like how you've aliased the elements in the `beforeEach` blocks - makes the tests nice and easy to read.
In many `before` blocks you're navigating the the `/profile/personal` page, waiting on the redirect, then clicking the link in the side panel to get to the page you want. Don't do this. You already have a test that confirms the redirect works, and that each link navigates to the correct page, so running those same steps in each test file just takes extra time but adds no value. Just navigate directly to the page you want to test and start testing.

2020-10-12 16:06 UTC, s-henney approved these changes
Looks good!

2020-10-12 18:25 UTC, merged